all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: 35.85.144.48
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/aws
        server-two:
          ansible_host: 34.217.16.197
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/aws
